### ISSUE TITLE
Enhance Image Preprocessing in Batch Generation

### ISSUE THREAD

**Issue by Dv04** [Dv04/Vision_Transformer#1]
Improve the image preprocessing steps within the batch_generator function to ensure optimal performance and accuracy. 

Consider exploring and implementing advanced techniques such as:

Data Augmentation: Techniques like rotation, zooming, and flipping to augment the training dataset.
Normalization: Normalize image pixel values for consistent model training.
Resizing: Ensure images are resized consistently to the expected input dimensions of the Vision Transformer model.

These enhancements are crucial for maintaining a consistent input format and potentially improving the model's performance.

**Comment by parth-verma7** [comment]
@Dv04 I would like to work upon this issue. Can you please assign it to me.

**Comment by Dv04** [comment]
Hey @parth-verma7, glad to have you with us.

Assigning you now.

**Comment by parth-verma7** [comment]
@Dv04 There is no train_ratio and validation_ratio mentioned in the notebook. I am assuming them myself.
Even there is no directory structure mentioned in the notebook, I found it mentioned in the issue - 'Implement Robust Dataset Splitting Mechanism'. It would be great if you mention this in the readme.md as well. It would be a comfort for the future contributors as well.
